- Dockerfile
Added
```
RUN echo ${RHEL_VERSION} > /etc/yum/vars/releasever \
&& yum config-manager --best --setopt=install_weak_deps=False --save
```
So that we don't need to add 
```
--releasever=${RELEASEVER} --setopt=install_weak_deps=False --best
```
to yum install commands in the driver container builds based on driver-toolkit.
/cc @zvonkok
> Adding yum config-manager and releasever settings to Dockerfile 

- Dockerfile
Setting an empty default value for `ARG` entries eliminates the need of the following downstream modifications:
```
- action: replace
match: 'ARG KERNEL_VERSION'
replacement: ''
- action: replace
match: 'ARG RT_KERNEL_VERSION'
replacement: ''
- action: replace
match: 'ARG RHEL_VERSION'
replacement: ''
```
https://github.com/openshift/ocp-build-data/blob/6861686494e12d5cbecde7d67f5ba01f4afe6323/images/driver-toolkit.yml#L10-L20
Using this bash's parameter expansion `${VAR:+-}` appends a `-` only if `$VAR` is not empty, eliminating the following downstream modifications:
```
- action: replace
match: '-${KERNEL_VERSION}'
replacement: ''
- action: replace
match: '-${RT_KERNEL_VERSION}'
replacement: ''
```
https://github.com/openshift/ocp-build-data/blob/6861686494e12d5cbecde7d67f5ba01f4afe6323 …
> Optionally set KERNEL_VERSION and RT_KERNEL_VERSION

- Dockerfile
Setting an empty default value for `ARG` entries eliminates the need of the following downstream modifications:
```
- action: replace
match: 'ARG KERNEL_VERSION'
replacement: ''
- action: replace
match: 'ARG RT_KERNEL_VERSION'
replacement: ''
- action: replace
match: 'ARG RHEL_VERSION'
replacement: ''
```
https://github.com/openshift/ocp-build-data/blob/6861686494e12d5cbecde7d67f5ba01f4afe6323/images/driver-toolkit.yml#L10-L20
Using this bash's parameter expansion `${VAR:+-}` appends a `-` only if `$VAR` is not empty, eliminating the following downstream modifications:
```
- action: replace
match: '-${KERNEL_VERSION}'
replacement: ''
- action: replace
match: '-${RT_KERNEL_VERSION}'
replacement: ''
```
https://github.com/openshift/ocp-build-data/blob/6861686494e12d5cbecde7d67f5ba01f4afe6323 …
> Bug 1945597: [release-4.7] Optionally set KERNEL_VERSION and RT_KERNEL_VERSION

- Dockerfile
Setting an empty default value for `ARG` entries eliminates the need of the following downstream modifications:
```
- action: replace
match: 'ARG KERNEL_VERSION'
replacement: ''
- action: replace
match: 'ARG RT_KERNEL_VERSION'
replacement: ''
- action: replace
match: 'ARG RHEL_VERSION'
replacement: ''
```
https://github.com/openshift/ocp-build-data/blob/6861686494e12d5cbecde7d67f5ba01f4afe6323/images/driver-toolkit.yml#L10-L20
Using this bash's parameter expansion `${VAR:+-}` appends a `-` only if `$VAR` is not empty, eliminating the following downstream modifications:
```
- action: replace
match: '-${KERNEL_VERSION}'
replacement: ''
- action: replace
match: '-${RT_KERNEL_VERSION}'
replacement: ''
```
https://github.com/openshift/ocp-build-data/blob/6861686494e12d5cbecde7d67f5ba01f4afe6323 …
> Bug 1945602: [release-4.6] Optionally set KERNEL_VERSION and RT_KERNEL_VERSION

- Dockerfile
The driver-toolkit should be shipped as part of the release payload, however the necessary label 
`LABEL io.openshift.release.operator=true`
is missing from the Dockerfile.
Relevant docs: https://docs.ci.openshift.org/docs/how-tos/onboarding-a-new-component/#product-builds-and-becoming-part-of-an-openshift-release-image
ART is able to patch this label in on their side, but in order for the driver-toolkit to also be a part of the ci release images, this fix needs to be added and back-ported.
> Bug 1959190: Add LABEL io.openshift.release.operator=true for addition to payload

- Dockerfile
Adding the last layer for mapping of the driver-toolkit to the correspoinding Node, SRO will pull the last layer of the release-payload, get the driver-toolkit URL and use the last layer of the driver-toolkit for mapping the right kernel versions.
> [release-4.8] Bug 1961656: Update Dockerfile

- Dockerfile
In RHEL 8, when a kernel module is loaded, the kernel checks the signature of the module against the public X.509 keys from the kernel system keyring (.builtin_trusted_keys) and the kernel platform keyring (.platform). The .platform keyring contains keys from third-party platform providers and custom public keys. The keys from the kernel system .blacklist keyring are excluded from verification.
> Requirements for authenticating kernel modules with X.509 keys

- Dockerfile
Docker reconciliation is failing in the ART pipelines due to the current $(arch) check. A suggestion to fix it was to rewrite these lines to be more similar to the previous $(arch) check.
> Rewrite architecture check for mokutil installation

- Dockerfile
For some driver container builds (e.g. NVIDIA driver) we need the gcc version which was used to build the kernel.
/cc @kpouget 
/cc @zvonkok
> Install gcc in driver-toolkit

- Dockerfile
The last PR to fix this was still not working in the ART pipeline. I assume this is because of the use of `[[ ... || ... ]]` instead of the POSIX compatible / sh compatible `[ ... ] || [ ... ]`
> Rearrange architecture check 

- Dockerfile
Image builds for the driver-toolkit are currently failing on aarch64 and s390x. Specifically the extract-vmlinux script is failing in the gcc install step.
This PR will change two things about the gcc install:
- In the case that we are unable to check vmlinux for which gcc version was used to compile the kernel, we should install gcc without a specified version.
- We should also be running yum clean all in this step.
> Fix GCC install on non-x86 and add yum clean all

- Dockerfile
This is a manual cherry-pick of the commits related to installing openssl, keyutils, and (architecture dependent) mokutil
/assign @zvonkok
>  [release-4.8] Bug 1972676: Requirements for authenticating kernel modules with X.509 keys 

- Dockerfile
The NVIDIA GPU operator currently requires entitlements to build the driver container, but the driver-toolkit could be used to prevent this. The problem is that the driver-toolkit is currently missing the gcc package needed for this driver-container. This is needed for RHODS.
The fix is to install gcc, specifically the version used to compile the kernel when available.
> [release 4.8] Bug 1974447: Cherry pick gcc to release 4.8

- Dockerfile
In versions of OCP where ART is specifying the kernel version as an argument to the driver-toolkit image build, the KERNEL_VERSION and RT_KERNEL_VERSION in /etc/driver-toolkit-release.json is missing the architecture at the end. Currently this is seen when comparing between DTK builds in 4.7 and 4.8
This results in unneeded inconsistencies between OCP versions, and means in some cases the kernel versions do not match with the node labels from NFD.
> Bug 1977972: /etc/driver-toolkit-release.json kernel version match rpm -q output

- Dockerfile
Currently, the Dockerfile tries to curl the extract-vmlinux script, which does not work in the ART build environment. This script is available as part of the kernel packages already installed in the location /usr/src/kernels/${INSTALLED_KERNEL}/scripts/extract-vmlinux, on x86 and aarch64.
In the other architectures, we can just install whichever gcc version is available by default in the ART builds.
This is needed in order for force the driver-toolkit to install the specific gcc version which was used to compile the kernel in the driver-toolkit.
> Bug 1979738: Remove curl of extract-vmlinux

- Dockerfile
extract-vmlinux does not work on aarch64 and s390x due to the kernel
formats used thereon.  This is more portable.
/cc @dagrayvid
> Bug 1988123: Use kernel config to determine GCC version

- Dockerfile
Cherry-pick of #50 and #56 to 4.6.
- Remove curl of extract-vmlinux, use installed script or install available gcc version
- Use kernel config to determine GCC version
> [release-4.6] Bug 1988127: Use kernel config to determine GCC version

- Dockerfile
- manifests/01-openshift-imagestream.yaml
- manifests/image-references
This PR adds a manifests/ directory, and a manifest for an imagestream. 
The imagestream contains a latest tag, and a tag for the RHCOS version corresponding to a release.
The string `0.0.1-snapshot-machine-os` will be substituted with the RHCOS version in the manifest. The substitution will happen when `oc adm release new ...` is run, and the rhcos version is scraped from the machine-os-content. 
See the `oc` code for information on how the substitution works. https://github.com/openshift/oc/blob/5d8dfa1c2e8e7469d69d76f21e0a166a0de8663b/pkg/cli/admin/release/image_mapper.go#L328-L334
Signed-off-by: David Gray <dagray@redhat.com>
> Add imagestream for driver-toolkit

- Dockerfile
- manifests/01-openshift-imagestream.yaml
- manifests/image-references
Reverts openshift/driver-toolkit#61, which reverted #60. It can now be un-reverted because the following PR has merged openshift/kubernetes#963. 
From the original PR:
> This PR adds a manifests/ directory, and a manifest for an imagestream.
> 
> The imagestream contains a latest tag, and a tag for the RHCOS version corresponding to a release.
> The string 0.0.1-snapshot-machine-os will be substituted with the RHCOS version in the manifest. The substitution will happen when oc adm release new ... is run, and the rhcos version is scraped from the machine-os-content.
> 
> See the oc code for information on how the substitution works. https://github.com/openshift/oc/blob/5d8dfa1c2e8e7469d69d76f21e0a166a0de8663b/pkg/cli/admin/release/image_mapper.go#L328-L334
> 
> Signed-off-by: David Gray …
> (reimplement) Add imagestream for driver-toolkit

- Makefile
- test/e2e
This PR adds an e2e test for the driver-toolkit, intended to be run in the OpenShift CI.
Currently the test is quite simple:
- Verify that the ImageStream/driver-toolkit exists
- Verify that the ImageStream/driver-toolkit tags are there (latest and RHCOS version) and that they match
- Verify that the kernel version in the driver-toolkit image matches the kernel version on a worker node.
Planned extensions of this testing include:
- Verify that the driver-toolkit also contains the right version of the real time kernel packages
- Build the simple-kmod on top of the driver-toolkit
Thanks to @kpouget for some ideas I borrowed from the gpu-operator testing in openshift-psap/ci-artifacts.
/cc @qbarrand @yevgeny-shnaidman @kpouget
> Add script to test driver-toolkit ImageStream and image contents

- test/e2e
As seen in [this failed test](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/24001/rehearse-24001-periodic-ci-openshift-driver-toolkit-master-4.9-e2e-aws-driver-toolkit/1463962933389168640/artifacts/e2e-aws-driver-toolkit/test/build-log.txt), the kubectl command is not available in the ci environment.
This was only there in error. Should have been `oc`.
> Replace kubectl command with oc in e2e test

- test/e2e
Needed in openshift CI. See failed test:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/24001/rehearse-24001-pull-ci-openshift-driver-toolkit-master-e2e-aws-driver-toolkit/1464052954045616128/artifacts/e2e-aws-driver-toolkit/test/build-log.txt
> Set explicit namespace for all oc commands

- OWNERS
Remove most PSAP team members from OWNERS and add members of the Partner Accelerators team.
> Add members of Partner Accelerators to OWNERS

- Makefile
- test/e2e
In some recently published z-stream releases of OCP, the driver-toolkit image contained the wrong kernel package versions. One measure we can take to avoid this going forward is to run an e2e test script against each nightly build of OCP to confirm the correct package versions are being installed.
We have been running this test as a periodic, using the e2e test from the master branch. To simplify the ci-operator configs for the driver-toolkit tests when adding them as release informing jobs, we should backport the e2e test to each branch we are testing against.
> Bug 2031854: Add e2e test to 4.9 branch

- README.md
The yum repos were removed from DTK by the ART team. In addition to the
technical reason for that, the logical reason is that DTK should already
include all the dependencies required for building an loading the
drivers (as this is the whole point of DTK to begging with), therefore,
there is no reason to install anything in the exampled described in the
documentation.
Also updated the way to get the driver-toolkit image for OCP release.
The short method can be interpreted differently on different
architectures  and the long version is more explicit.
---
We already have some consumers that are hitting this issue as the documentation show how to install packages although the yum repos where already removed from the image. …
> Updating README.md.

- README.md
This makefile target was removed from the simple-kmod makefile and is no
longer needed.
---
Was removed [here](https://github.com/openshift-psap/simple-kmod/pull/1).
> Removing the 'make buildprep' from README.md.

- manifests/01-openshift-imagestream.yaml
- manifests/image-references
The imagestream contains a latest tag, and a tag for the RHCOS version
corresponding to a release.
The string 0.0.1-snapshot-machine-os will be substituted with the RHCOS
version in the manifest.
The substitution will happen when oc adm release new ... is run, and the
rhcos version is scraped from the machine-os-content.
Co-authored-by: David Gray <40244437+dagrayvid@users.noreply.github.com>
---
See the oc code for information on how the substitution works. https://github.com/openshift/oc/blob/5d8dfa1c2e8e7469d69d76f21e0a166a0de8663b/pkg/cli/admin/release/image_mapper.go#L328-L334
This is to revert it removal at https://github.com/openshift/driver-toolkit/pull/79
> Add imagestream for driver-toolkit.

- README.md
ubi-minimal is a leaner image.
As ubi-minimal doesn't contain the dnf package, we make use of the microdnf package instead.
> Replacing last layer image in driver-container documentation from ubi8 to ubi8/ubi-minimal

- Dockerfile
ART is looking into the content of this dir in order to deploy
additional manifests with OCP.
This is needed in order to deploy DTK's imagestream to the cluster.
---
This PR follows up on https://github.com/openshift/driver-toolkit/pull/81 in order to bring back the imagestream that was accidentally removed in https://github.com/openshift/driver-toolkit/pull/79.
> Bug 2087026: Adding manifests/ inside DTK container image.

- README.md
README.md lacks the instructions for loading/unloading the additional module simple-procfs-kmod in example. Added to modprobe example.
> Bug 2087114: Add simple-procfs-kmod in modprobe example in README.md 

- README.md
In the last layer, instead of installing `kmod` using micro-dnf we will
now just copy `kmod` binary from the builder stage.
In a disconnected env, we wouldn't not be able to run micro-dnf commands
at build time.
> Bug 2035488: Updating the doc for multi-stage driver containers.

- test/e2e
Jobs using this e2e script are peramfailing with errors like this:
```
+ oc debug --image-stream=openshift/driver-toolkit:latest -n openshift --quiet -- bash -c 'echo "$SOURCE_GIT_URL/commit/$SOURCE_GIT_COMMIT"'
Error from server (Forbidden): pods "image-debug" is forbidden: violates
PodSecurity "restricted:latest": allowPrivilegeEscalation != false
(container "debug" must set
securityContext.allowPrivilegeEscalation=false), unrestricted
capabilities (container "debug" must set
securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or
container "debug" must set securityContext.runAsNonRoot=true),
seccompProfile (pod or container "debug" must set
securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```
> OCPBUGS-999: Use privileged namespace for oc debug commands

- Dockerfile
Those packages are needed in order to compile the kernel since 4.16.
In addition to that, some kernel-modules needs them as well in order to compile.
---
Fixes https://github.com/openshift/driver-toolkit/issues/89
> Adding 'flex' and 'bison' to the driver-toolkit image.

- README.md
> Adjusting the documentation to refer to KMM instead of SRO.

- manifests/01-openshift-imagestream.yaml
- manifests/image-references
- test/e2e
As part of https://github.com/openshift/enhancements/blob/master/enhancements/ocp-coreos-layering/ocp-coreos-layering.md we have switched to a new `rhel-coreos-8`.
Really, nothing else besides the MCO should be pulling in or referencing the OS images.  I don't understand what cross-checking the image stream tag was ever doing at all.  The MCO owns rolling out the right OS version, and if that isn't correct something else went seriously wrong.
Closes: https://github.com/openshift/driver-toolkit/issues/101
> Stop pulling in `machine-os-content`

- manifests/01-openshift-imagestream.yaml
- manifests/image-references
- test/e2e
This reverts commit d059f659486fea07d09def1793dc75ef91ad6cf4.
SRO and KMM use the DTK ImageStream tag that corresponds to the current RHEL CoreOS release.
Reverting the commit that removed the tag from the `ImageStream`.
> Revert "Stop pulling in `machine-os-content` (#102)"

- ci/prow/check-commits-count
Add check-commit-counts script to use with ci-operator
in order to check that PRs have only one single commit.
> Add check-commit-counts script

- docs/driver_toolkit_imagestream.md
This imagestream, its complexity, and its moving part seems to be confusing a lot of people, therefore, having a single place in which we are documenting all the involved teams and moving parts is crucial for preventing breaking changes.
> Adding documentation regarding the driver-toolkit imagestream.

- Dockerfile
rpmbuild in the DTK helps when having to rebuild source kernel module RPMs to match the RHCOS kernel version
> Adding rpm-build to the Dockerfile

- ci/prow/check-commits-count
> Fixing `check-commits-count` to work on other branches than `master`.

- Dockerfile
The string representing the GCC version has changed between RHEL 8.6 and RHEL 9.2.
In 8.6 it looks like:
```
$ cat /lib/modules/<kernel version>/config | grep gcc
Compiler: gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-10) 
```
In 9.2 it looks lie:
```
$ cat /lib/modules/<kernel version>/config | grep gcc
CONFIG_CC_VERSION_TEXT="gcc (GCC) 11.3.1 20221121 (Red Hat 11.3.1-4)"
```
---
Basically I have just removed the word `Compiler` from the regexp. All the rest is just cosmetics.
> OCPBUGS-11119: Fixing the regexp used to get the correct GCC version.

- Dockerfile
This commit has no real effect as the `kernel[-rt]-core` package is a dependency of the `kernel[-rt]-modules` package, therefore, it will be installed even if not mentioned explicitly.
Having it in the Dockerfile raise some questions such as:
* Why do we need this package in order to build kernel modules?
* Why are we publishing RHEL content for a kernel that may never ship with RHEL?
Removing it from the Dockerfile and let `dnf` resolve it dependencies by its own seems like a better approach.
> OCPBUGS-12287: Removing `kernel[-rt]-core` packages from the image.

- docs/driver_toolkit_imagestream.md
- manifests/image-references
The `machine-os-content` is deprecated and we'd like to stop shipping it entirely in the release payload. Point the DTK imagestream to the `rhel-coreos` image instead.
Closes: #101
> MCO-392: Start using `rhel-coreos` image rather than `machine-os-content`

- docs/driver_toolkit_imagestream.md
- manifests/image-references
This reverts commit 86bbea7aadc5a6f6214c6d3bd95f40096725fee8.
We need to revert the openshift/os side of this because of remaining references to machine-os-content:
https://github.com/openshift/os/pull/1393
So we have to revert this too.
> Revert "Start using `rhel-coreos` image rather than `machine-os-content` (#135)"

- Dockerfile
Some drivers may have parts written in C++. This change add the `gcc-c++` package to the image, in order to compile these drivers. Like for the `gcc` package, the version is pinned to the one used to build the kernel and defaults to the latest.
> MGMT-16313: Add support for C++ build

- Dockerfile
RHEL 9 and RHCOS for 4.15 are adding support for installing a 64k pages size ARM kernel at runtime, with the `kernelType: '64k-pages'` attribute in the MachineConfig specification. When applied, the kernel is switched to the `+64k` version, e.g. `5.14.0-284.41.1.el9_2.aarch64` becomes `5.14.0-284.41.1.el9_2.aarch64+64k`.
From a Driver Toolkit perspective, the user should be able to use a kernel version suffixed by `+64k` at build time. This is provided by the `kernel-64k` packages.
This change adds the relevant packages to the driver toolkit image when the architecture is `aarch64`.
> MGMT-16701: Add support for 64k pages with ARM64

- manifests/01-openshift-imagestream.yaml
Similar to
https://github.com/openshift/cluster-samples-operator/pull/482, we want CVO managed imagestreams to have the importMode as preserveOriginal so that it imports the manifestlisted image with all arches so that it works on a multi-arch compute cluster
> IR-192: Add importMode and set it to PreserveOriginal to import the manifestlisted image

- Dockerfile
In OKD, we will always want to keep the "RHEL_VERSION" set by the base CentOS stream image used to build the dtk image.
> OKD-40: Use a default RHEL_VERSION when the build argument is not specified

- Dockerfile
Since 4.16, the kernel and the rt-kernel are coming rom the same repository, therefore, they need to be differentiated explicitly in order to match the new kernel version format for the RT kernel.
Example for the new RT kernel version format:
```
5.14.0-427.18.1.el9_4.x86_64+rt
```
---
/cc @yevgeny-shnaidman @cdvultur
> OCPBUGS-33699: Adding the `+` char to the RT kernel version.

- Dockerfile
Summary: Meta package to install matching core and devel packages for a given kernel.
AMD, needs this package in order to build their kmods.
> MGMT-19342: Adding the `kernel-devel-matched` package.

- test/e2e
We are validating that the DTK image contain the kernel packages matching the running kernel on the node.
This commit is extending the job to also compare DTK's kernel-rt packages and the RT kernel that the node will reboot into if configured to do so.
> MGMT-19632: Extending the `e2e` job to validate the `kernel-rt` versions matches.

- test/e2e
`yq` is not installed in the image that runs the job on nightly builds. It is installed on the pre-merge job though, therefore, it wasn't catch during PR creation.
This commit should fix the issue.
---
/assign @yevgeny-shnaidman @TomerNewman 
Nightly builds are currently failing because the `yq` tool doesn't exist in the test image.
> MGMT-19671: Using `jq` instead of `yq` in the `e2e` job.

- test/e2e
This job is running on OCP nightly builds and the OCP payload for those versions aren't available in quay.io but instead they are in `registry.ci.openshift.org`.
---
/assign @yevgeny-shnaidman @TomerNewman
> MGMT-19688: Pulling the DTK image from the CI registry instead of quay.io.

- test/e2e
In order to access the release payload, we need to have access to the pull-secret of the cluster.
In addition, since we are running in a "hub" cluster, `podman` cannot be used, therefore, I have replaced it with an `oc run ...` command instead.
> MGMT-19688: Adding pull-secrets to the `oc adm release info...` command.

- test/e2e
OCP 4.19 has recently bumped its RHEL version from 9.4 to 9.6. With this change, seems like the
`/usr/share/rpm-ostree/extensions/kernel-rt-<version>...` file is gone so the test has been adjusted to get the version from the `/usr/share/rpm-ostree/extensions/kernel-rt-core-<version>...` file instead.
---
/assign @TomerNewman @yevgeny-shnaidman 
In the recent containers:
```
root gpu-operator (main) $ oc adm release info registry.ci.openshift.org/ocp/release:4.19.0-0.nightly-2025-01-19-034009 --image-for=rhel-coreos-extensions
quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:297ff1d0d9e4ecd2f48ba50cfe07e88f5bb3f6379c27786fba5768f63fa9b000
root gpu-operator (main) $ podman run -it --rm quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:297ff1d0d9e4ecd2f48ba50cfe07e88f5bb3f6379c27786f …
```
> MGMT-19747: Getting the kernel version from the `kernel-rt-core-*` file.

- test/e2e
We're working on changing how the node image is built to more cleanly be a layered build on top of a RHEL-only base image. As a result, some of the fields in `/etc/os-release` are changing slightly. The changes are documented in:
https://github.com/openshift/enhancements/blob/master/enhancements/rhcos/split-rhcos-into-layers.md#etcos-release
Though one bit missing from there is that `RHEL_VERSION` is no longer in `/etc/os-release`. That info is now simply `ID`. So use that instead.
> NO-JIRA: test/e2e: adapt for layered node image

- Dockerfile
The VERSION variable in `/etc/os-release` contains also the name of the major version. In the RHEL 9 case, it adds ` (Plow)` to the `releasever` variable. We don't know how DNF is using it, but it creates a risk.
This pull request modifies the environment variable to use the `VERSION_ID`, which contains only the RHEL minor version.
It also modifies the DNF variables folder to `/etc/dnf/vars` to comply with DNF configuration and remove a _legacy_ setting.
Signed-off-by: Fabien Dupont <fdupont@redhat.com>
> MGMT-20889: Use VERSION_ID for RHEL minor version
